### ISSUE TITLE
Some problems cause the project to report an error

### ISSUE THREAD

**Issue by ajuner** [hackycy/sf-egg-admin#11]
https://github.com/hackycy/sf-egg-admin/blob/1367a9969dc5c791f5d482121b5f20e9cc2cd412/app/dto/comm.ts#L29
这里的参数值是不是应该取TransformFnParams的value
```
@Transform({ value: v } => parseInt(v), { toClassOnly: true }) 
```

**Comment by hackycy** [comment]
看这个链接：https://github.com/typestack/class-transformer/tree/v0.3.2#basic-usage，目前还未依赖最新版本。

**Comment by ajuner** [comment]
🤣
