### ISSUE TITLE
有没有可能加个普通用户端逻辑(应该是app、H5端，普通用户提交个表单的业务之类，系统用户在PC端查看的场景)？

### ISSUE THREAD

**Issue by LDXu** [hackycy/sf-egg-admin#12]
## Feature request（新功能建议）

当前项目定位是一个公司内部的部分。
如果基于当前项目做成支持公司及对外用户使用的话，是否只要这样修改就可以了？
1.新增一个部门和一个角色，给普通用户使用(参考：系统用户体系)
2.user控制器和服务器新增一个普通用户注册功能，写死部门和角色(参考：新增系统用户)
3.新增一个普通用户的路由装饰器（参考：添加/admin前缀的Url路由装饰器）
4.定义一个用户token验证(参考：Admin权限验证中间件，但是这个普通用户是不需要权限)
5.普通用户业务开发即可

**Comment by hackycy** [comment]
@LDXu 3、4点可以，但是1、2点不赞同。后台的用户系统跟具体app端、h5端的用户系统分开即可，无需再做鉴权。

**Comment by LDXu** [comment]
好的
