### ISSUE TITLE
yaml.safeLoad 位置问题

### ISSUE THREAD

**Issue by songjiachao** [hackycy/sf-egg-admin#7]
getErrorMessageByCode(code: string) {
    const errorMap = yaml.safeLoad(fs.readFileSync(path.resolve(__dirname, '../../config/error_constants.yaml'), 'utf8'));
    return errorMap[code];
  },
这样写是不是每次都会读文件，导致性能问题，是不是可以将errorMap放到代码外面，只执行一次

**Comment by hackycy** [comment]
@songjiachao 的确没改之前每次会读取配置文件。这个想法挺好的的，可以优化的。
