### ISSUE TITLE
有考虑迁移到midway吗

### ISSUE THREAD

**Issue by cckowin** [hackycy/sf-egg-admin#8]
midway的ts支持好像更完善点，也自带路由装饰器，typeorm集成和参数校验，这样是不是能简化代码
还有个问题代码里很多地方用到了any，按照typescript规范尽量少用any是不是应该用unkown吗

**Comment by hackycy** [comment]
@cckowin 
简化代码也是相对于midway而言吧，该项目里的TypeORM那些已经封装成插件使用了。至于迁移的话，目前想法是先稳定和优化前端和后端的代码。后续再考虑进行迁移。
至于any和unkownn看习惯吧，unkownn代码会严谨些。
