### ISSUE TITLE
service中的错误如何处理啊

### ISSUE THREAD

**Issue by cckowin** [hackycy/sf-egg-admin#9]
一般情况下都是Controller返回错误码，如果要在Service中处理返回错误码的话如何统一处理啊，因为有很多情况下某一个功能放在某个servcice里面了，这样是只能通过返回值不同来进行错误处理了吗

**Comment by hackycy** [comment]
@cckowin 
service报错不做处理的一般是系统内置的错误了吧，不是业务类型的错误不应该返回给客户端的。

你的需求也可以解决，在中间件的层面处理就可以了，系统里面有一个exception的错误处理中间件，你可以在里面判断。
在需要的service中统一抛出一个异常，在中间件判断是否是这个类型的异常然后做相应的处理就可以了。

**Comment by cckowin** [comment]
恩，不过比如我有一个存放程序的表，里面有程序号的字段，我的业务逻辑放在了service里面，当我有个更新请求的去更新这个表的程序号的时候我会去判断下新传的数据号存不存在，存在的话返回数据号已存在这是一个业务类型的错误，如果我放在service里判断，一个service就好了，如果我放在controller里面的话，需要把这个service拆分成取数据的service和更新的service然后在controler里面组装

**Comment by hackycy** [comment]
@cckowin 
你可以直接在service层直接返回请求结果内容，可以不必要统一的放在controller层。我的目的是分清controller层和service层逻辑的处理。
我是觉得拆分开来会好点，就是判断会多一些，但是从controller层捋一捋就能看清楚逻辑，而不必要再去看service层是如何处理的。但统一处理也可以采用中间件方式来做。

你的这种其实也算是一个参数合法性校验吧，之前也是觉得定义的DTO能够处理这种参数的规则校验就好了，但是没有思路，只能靠service返回值判断了。

**Comment by cckowin** [comment]
恩，就是有时候不知道如何区分controller和service的边界了，都在controller判断的话，有的service都是调用一下entity，controller里面放业务逻辑了

**Comment by hackycy** [comment]
@cckowin 
区分不了就细化一下，controller只做业务的逻辑判断，拿数据或者数据的处理在service下处理。无法通过返回值就直接抛出异常，controller层有需要就接管异常，不接管的异常就是非业务类型的错误就丢到中间件层处理。

这些都只是规则，也可以不遵循的。主要看个人或者项目里团队协作下是怎么处理的遵循就好了。

**Comment by cckowin** [comment]
恩，或者可以把程序的返回封装成两个函数this.success()和this.fail()，在this.success()返回成功的的结果，在this.fail()里面抛出一个自定义的业务异常，这样就可以在controller和service里面都可以抛出业务异常了，然后在异常处理的中间件里统一返回失败的结果，非业务的异常还是用throw Error()抛出，这样就能统一处理了
